### ISSUE TITLE
Is this package dead?

### ISSUE THREAD

**Issue by oemer-aran** [cwsdigital/tailwind-utopia#14]
Can't download this package with `yarn add --save-dev cwsdigital/tailwind-utopia`

**Comment by pauldwight** [comment]
The package isn't registered on a registry. With npm you it covers this and clones from the github -  I am not sure about yarn - you might need to reference the github repo.
```bash
yarn add '<tailwind-utopia>@https://github.com/cwsdigital/tailwind-utopia'
```

Reference: https://github.com/yarnpkg/berry/issues/994#issuecomment-628586986
