### ISSUE TITLE
Cannot install with Tailwind 3

### ISSUE THREAD

**Issue by klickreflex** [cwsdigital/tailwind-utopia#6]
Hey, thanks for this nice plugin.

When trying to install I'm getting 1.0.4 from NPM, is it possible that 1.0.5 has not been published to the registry?

```
npm install --save-dev cwsdigital/tailwind-utopia 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: projectxyz.com@undefined
npm ERR! Found: tailwindcss@3.0.24
npm ERR! node_modules/tailwindcss
npm ERR!   dev tailwindcss@"^3.0.24" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@"^2" from tailwind-utopia@1.0.4
npm ERR! node_modules/tailwind-utopia
npm ERR!   dev tailwind-utopia@"cwsdigital/tailwind-utopia" from the root project
npm ERR! 
```

Installing directly from Github using the version tag does work though: `npm i --save-dev git+https://github.com/cwsdigital/tailwind-utopia.git#v1.0.5`

**Comment by ianhobbs** [comment]
ditto

**Comment by merchako** [comment]
Is NPM ever going to get updated? I'm wondering if maybe this project has been abandoned and if I should avoid it.

**Comment by pauldwight** [comment]
@merchako This has been updated, sorry it had fallen off our list.
